<div id="youtube_search" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="youtube_modal_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="youtube_modal_label"><?php echo $this->modelTitle; ?></h4>
            </div>
            <div class="modal-body">
                <form class="form-inline">
                    <div class="input-group col-sm-12">
                        <input type="text" class="form-control" id="youtube_search_term" />
                        <a href="#" id="youtube_search_btn" class="input-group-addon"><span class="glyphicon glyphicon-search"></span></a>
                    </div>
                </form>
                <div id="youtube_search_results">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
</div>