<div class="row">
    <?php foreach($this->videoFeed as $videoEntry): ?>
    <?php $thumbs = $videoEntry->getVideoThumbnails(); ?>
	<div class="col-xs-6 col-md-3" id="youtube_info_<?php echo $videoEntry->getVideoId(); ?>">

            <a href="#<?php echo $videoEntry->getVideoId(); ?>" class="thumbnail">
                <img src="<?php echo $thumbs[0]['url']; ?>" />

                <div class="caption" title="<?php echo $videoEntry->getVideoTitle(); ?>">
                    <h3><?php echo $videoEntry->getVideoTitle(); ?></h3>
                    <?php /* <p><?php echo $videoEntry->getVideoDescription(); ?><p> */ ?>
                </div>
            </a>

	</div>
    <?php endforeach; ?>
</div>