<li<?php echo $this->nav->visible ? '' : ' class="not-visible"'; ?>
    id="layout_nav_<?php echo $this->nav->id; ?>">
    <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
    <span class="nav-label"><?php echo $this->nav->label; ?></span>
    <div class="actions pull-right">

        <a class="toggle" href="#<?php echo $this->nav->id; ?>"
           title="Exibir / Ocultar" rel="tooltip">
            <span class="glyphicon glyphicon-eye-<?php echo $this->nav->visible ? 'open' : 'close'; ?>"></span>
        </a>

        <a class="edit" href="#<?php echo $this->nav->id; ?>"
           title="Editar" rel="tooltip"><span class="glyphicon glyphicon-edit"></span></a>

        <a class="remove" href="#<?php echo $this->nav->id; ?>"
           title="Excluir" rel="tooltip"><span class="glyphicon glyphicon-remove"></span></a>
    </div>
    <ul class="nav-container"></ul>
</li>