<?php

function printPages($pages, $baseUrl) {
    if ($pages) {
        echo '<ul class="nav-container list-unstyled">';
        foreach ($pages as $nav) {
            echo '<li' . ($nav->visible ? '' : ' class="not-visible"') . 
                ' id="layout_nav_' . $nav->id. '">' .
                '<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>' .

                '<span class="nav-label">' . $nav->label . '</span>' .
                ' <span class="label label-default" title="Id">'/* . 'layout_nav_'*/ . $nav->id . '</span>' .

                '<div class="actions pull-right">' .

                    '<a class="toggle" href="#' . $nav->id . '" title="Exibir / Ocultar" rel="tooltip">' .
                    '<span class="glyphicon glyphicon-eye-' . ($nav->visible ? 'open' : 'close')  . '"></span></a> ' .

                    '<a class="edit" href="#' . $nav->id . '" ' .
                       'title="Editar" rel="tooltip"><span class="glyphicon glyphicon-edit"></span></a> ' .

                    '<a class="remove" href="#' . $nav->id . '" ' .
                       'title="Excluir" rel="tooltip" class="remove"><span class="glyphicon glyphicon-remove"></span></a>' .

                '</div>';

                if(isset($nav->pages) && $nav->pages) {
                    printPages($nav->pages, $baseUrl);
                } else {
                    echo '<ul class="nav-container list-unstyled"></ul>';
                }
            echo '</li>';
        }
        echo '</ul>';
    }
}

?>

<div class="page-header">
    <div class="btn-group pull-right">
      <a class="btn btn-default pull-right"
            href="<?php echo $this->adminBaseUrl('layout/nav') ?>">
             <span class="glyphicon glyphicon-refresh"></span> Recarregar
         </a>
    </div>
    <h1>
        <span class="glyphicon glyphicon-th-large"></span> 
        Layout
        <small>Menus</small>
    </h1>
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Gerenciar menus</h3>
    </div>
    <div class="panel-body">
        <ul class="list-unstyled">
            <li class="new-nav-item">
                <span class="glyphicon glyphicon-plus"></span>
                Adicionar novo item de menu
            </li>
        </ul>

        <?php if($this->navConfigs):
            printPages($this->navConfigs, $this->baseUrl());
        else: ?>
        <ul class="nav-container ui-sortable list-unstyled"></ul>
        <?php endif; ?>
    </div>    
</div>