<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-th-large"></span> 
        Layout
        <small>Páginas</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Cadastrar página</h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form; ?>        
    </div>    
</div>