<div class="page-header">
    <div class="btn-group pull-right" id="shortcuts_btn">
        <a class="btn btn-default"
           href="<?php echo $this->adminBaseUrl("layout/page/config/id/{$this->page->id}"); ?>">
            <span class="glyphicon glyphicon-refresh"></span> Recarregar
        </a>
        <?php if($this->page->id_content || $this->page->id_content_type): ?>
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="glyphicon glyphicon-edit"></span> Editar este layout
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="<?php echo $this->adminBaseUrl("layout/page/edit/id/{$this->page->id}"); ?>"
                   ><span class="glyphicon glyphicon-edit"></span> Editar este layout</a>
            </li>
            <?php if($this->page->id_content): ?>
            <li>
                <a href="<?php echo $this->adminBaseUrl("content/content/"
                    . "edit/id/{$this->page->id_content}");
                    ?>"><span class="glyphicon glyphicon-edit"></span> Editar conteúdo</a>
            </li>
            <?php elseif($this->page->id_content_type): ?>
            <li>
                <a href="<?php echo $this->adminBaseUrl("content/content-type/"
                    . "edit/id/{$this->page->id_content_type}");
                    ?>"><span class="glyphicon glyphicon-edit"></span> Editar tipo de conteúdo</a>
            </li>
            <?php endif; ?>
        </ul>
        <?php else: ?>
            <a class="btn btn-default" href="<?php echo 
                $this->adminBaseUrl("layout/page/edit/id/{$this->page->id}"); ?>">
                <span class="glyphicon glyphicon-edit"></span> Editar este layout
            </a>
        <?php endif; ?>
    </div>
    <h1>
        <span class="glyphicon glyphicon-th-large"></span> 
        Layout
        <small>Configurar</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Elementos</h3>
            </div>
            <div class="panel-body">  
                <ul id="areas_list" class="list-group">

                            <li class="area">
                                <span class="icon-large icon-one-column"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-12">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                            <li class="area">
                                <span class="icon-large icon-two-columns"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-6">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-6">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                            <li class="area">
                                <span class="icon-large icon-two-columns-left"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-4">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-8">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                            <li class="area">
                                <span class="icon-large icon-two-columns-right"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-8">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-4">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                            <li class="area">
                                <span class="icon-large icon-three-columns"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-4">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-4">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-4">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                            <li class="area">
                                <span class="icon-large icon-three-columns-main"></span>
                                <div class="pull-right options">
                                    <a href="#remove" rel="tooltip" title="Remover"
                                    class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                </div>
                                <div class="columns">
                                    <div class="column-wrapper col-md-3">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-6">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                    <div class="column-wrapper col-md-3">
                                        <div class="column"><ul></ul></div>
                                        <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                    </div>
                                </div>
                                <span class="clearfix"></span>
                            </li>

                        </ul>
                
                <div class="panel-group" id="blocks_list" role="tablist" aria-multiselectable="true">
                    <?php foreach($this->blocks as $moduleName => $blocks): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="heading_<?php echo $moduleName; ?>">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#blocks_list" href="#module_<?php echo $moduleName; ?>" aria-expanded="true" aria-controls="#module_<?php echo $moduleName; ?>">
                                    <?php echo $moduleName; ?>
                                </a>
                            </h4>
                        </div>
                        <div id="module_<?php echo $moduleName; ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_<?php echo $moduleName; ?>">
                                <ul class="nav nav-list">
                                    <?php foreach($blocks as $blockId => $blockName):
                                        if ($blockId != 'layout-column'): ?>
                                    <li class="block">
                                        <input type="hidden" value="<?php echo $blockId; ?>"
                                               name="areas[][columns][][blocks][]" />
                                        <a href="#" class="block-description"><?php echo $blockName; ?></a>
                                        <div class="pull-right options">
                                            <a href="#remove" rel="tooltip" title="Remover"
                                            class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                        </div>
                                        <span class="block-id label label-default"><?php echo $blockId; ?></span>
                                    </li>
                                    <?php endif;
                                    endforeach; ?>
                                </ul>
                        </div><!--/panel-collapse-->
                    </div><!--/panel-->
                    <?php endforeach; ?>
                </div><!--/panel-group-->

            </div><!--.panel-body -->
        </div><!--.panel -->
    </div>

    <div class="col-md-9">
        <form id="layout_form_config" action="<?php echo $this->adminBaseUrl('layout/page/update') ?>" method="post">
            <input type="hidden" name="id_layout_page" value="<?php echo $this->page->id; ?>" />
            <input type="hidden" name="remove_blocks" id="remove_blocks" />
            
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->escape($this->page->page); ?></h3>
                </div>
                <div class="panel-body"> 

                    <div id="layout_body">
                        <ul class="list-unstyled">
                            <?php
                            $areas = $this->page->getBlocks();
                            if ($areas) foreach($areas as $area):
                                $columns = $area->getBlocks();
                            ?>
                            <li id="block_<?php echo $area->id; ?>" class="area">
                                <input type="hidden" value="<?php echo $area->id; ?>" name="areas[<?php echo $area->id; ?>][id]" class="layout-area-id" />
                                <div class="columns">
                                    <?php if ($columns) foreach($columns as $column):
                                        $columnOptions = $column->getOptions();?>
                                        <div class="column-wrapper <?php echo $column->getOption('class'); ?>">
                                            <div id="block_<?php echo $column->id; ?>" class="column">
                                                <input type="hidden" class="layout-column-id" name="areas[<?php echo $area->id; ?>][columns][<?php echo $column->id; ?>][id]" value="<?php echo $column->id; ?>" />
                                                <input type="text" readonly="readonly" class="layout-column-class pull-left" name="areas[<?php echo $area->id; ?>][columns][<?php echo $column->id; ?>][class]" value="<?php echo $column->getOption('class'); ?>" />
                                                <div class="pull-right options">
                                                    <a href="#toggle" rel="tooltip"  class="toggle" title="Exibir/ocultar coluna"><span class="glyphicon glyphicon-eye-<?php echo $column->isVisible() ? 'open' : 'close'; ?>"></span></a>
                                                    <a rel="tooltip" title="Configurar coluna" href="#setup" class="setup"><span class="glyphicon glyphicon-wrench"></span></a>
                                                    <a href="#remove" rel="tooltip" title="Remover coluna" class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                                </div>
                                                <ul class="list-unstyled">
                                                    <?php
                                                    $blocks = $column->getBlocks();
                                                    if ($blocks) foreach($blocks as $block):
                                                        $blockOptions = $block->getOptions(); ?>
                                                    <li id="block_<?php echo $block->id; ?>" class="block<?php echo $block->isVisible() ? '' : ' disabled'; ?>">
                                                        <input type="hidden" value="<?php echo $block->id; ?>" name="areas[<?php echo $area->id; ?>][columns][<?php echo $column->id; ?>][blocks][]" />
                                                        <div class="pull-right options">
                                                            <a href="#toggle" rel="tooltip"  class="toggle" title="Exibir/ocultar bloco"><span class="glyphicon glyphicon-eye-<?php echo $block->isVisible() ? 'open' : 'close'; ?>"></span></a>
                                                            <a rel="tooltip" title="Configurar bloco" href="#setup" class="setup"><span class="glyphicon glyphicon-wrench"></span></a>
                                                            <a href="#remove" rel="tooltip" title="Remover bloco" class="remove"><span class="glyphicon glyphicon-remove"></span></a>
                                                        </div>
                                                        <span class="block-name label label-primary"><?php echo $block->hasOption('title') && $block->getOption('title') ? $this->escape($block->getOption('title')) : ''; ?></span>
                                                        <span class="block-id label label-default"><?php echo $this->escape($block->block); ?></span>
                                                    </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            </div>
                                            <div class="splitter" title="Dividir coluna"><span>|</span></div>
                                        </div>
                                    <?php endforeach; ?>
                                    <span class="clearfix"></span>
                                </div>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                        <span class="clearfix"></span>
                    </div><!-- #layout_body -->

                </div><!--.panel-body -->
                <div class="panel-footer">
                    <button type="submit" name="save" class="btn btn-primary btn-lg" value="Salvar" id="save_layout">Salvar</button>
                    <button type="submit" name="cancel" class="btn btn-default btn-lg" value="Cancelar">Cancelar</button>
                </div>
            </div><!--.panel -->
        </form>
    </div>

</div>