<div class="modal fade" id="block_setup" tabindex="-1" role="dialog" aria-labelledby="block_setup_label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="block_setup_label">Configurações de bloco</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->form; ?>
            </div>
        </div>
    </div>
</div>