<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5); ?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="jaimeneto.com">
    <meta name="description" content="PHP Content Management Framework powered by Zend Framework">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<?php
    $this->syncLayoutFiles('img', 'default', 'backend');
    $this->headTitle()->setSeparator(' - ')->append('FrontZend');
    echo $this->headTitle() . PHP_EOL;

    $cssFiles = array(
        'lib/bootstrap/css/bootstrap.min.css',
        'lib/jquery/jquery-ui-1.11.2.custom/jquery-ui.min.css',
        'lib/jquery/plugins/jquery-treetable/stylesheets/jquery.treetable.css',
        'lib/jquery/plugins/treeview/jquery.treeview.css',
        'lib/valums-file-uploader/client/fileuploader.css',
    );
    $modulesDir = new DirectoryIterator(APPLICATION_PATH . '/modules');
    foreach($modulesDir as $moduleDir) {
        if (!$moduleDir->isDot() && 
                is_dir($moduleDir->getPathname() . '/views/css'))
        {
            $cssDir = new DirectoryIterator($moduleDir->getPathname() . '/views/css');
            foreach($cssDir as $cssFile) if ($cssFile->isFile()) {
                $cssFiles[] = $cssFile->getPathname();
            }
        }
    }

    $cssFiles[] = APPLICATION_PATH . '/layouts/backend/default/css/style.css';
    echo $this->cssHeadLinks($cssFiles, 'default', 'backend', false, false);
?>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="<?php echo $this->baseUrl('cache/layouts/backend/default/img/favicon.png'); ?>" />
</head>

<body class="backend">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <?php echo $this->navbarHeader('FrontZend', 'navbar-collapse-1', $this->adminBaseUrl()); ?>
        </div><!-- /.container -->
    </nav>
    </div>
    
    <main>
    
        <div class="container">

            <div class="row">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <div class="panel-title">Página não encontrada!</div>
                    </div>
                    <div class="panel-body text-center">
                        <?php echo $this->layout()->content; ?>
                        <br /><br /><br />
                        <a href="<?php echo $this->baseUrl('/'); ?>" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-home"></span> 
                            Voltar para a página principal</a>
                        <br /><br /><br />
                    </div>
                </div>
            </div>

        </div> <!-- /container -->

        <footer>
            <div class="copyright">
                <div class="container">
                    &copy; 2013-<?php echo Zend_Date::now()->get('YY'); ?> <a href="http://www.jaimeneto.com" target="_blank">JAIMENETO.COM</a>

                    <a href="http://frontzend.jaimeneto.com" target="_blank" class="pull-right">
                        <span class="glyphicon glyphicon-link"></span>
                        frontzend.jaimeneto.com
                    </a>
                </div> <!-- /container -->
            </div>
        </footer>
    
    </main>
    
    <?php
    $jsFiles = array(
        'lib/jquery/jquery-1.11.1.min.js',
        'lib/jquery/jquery-ui-1.11.2.custom/jquery-ui.min.js',
        'lib/jquery/plugins/jquery-mask-v0.7.4/jquery.mask.min.js',
        'lib/tiny_mce/jquery.tinymce.js',
        'lib/valums-file-uploader/client/fileuploader.js',
        'lib/bootstrap/js/bootstrap.min.js',
        'lib/jquery/plugins/jquery-treetable/javascripts/src/jquery.treetable.js',
        'lib/jquery/plugins/treeview/jquery.treeview.min.js',
        'lib/edit_area/edit_area_full.js',
        APPLICATION_PATH . '/layouts/backend/default/js/functions.js',
        APPLICATION_PATH . '/layouts/backend/default/js/twitter-bootstrap.js',
    );
    $modulesDir = new DirectoryIterator(APPLICATION_PATH . '/modules');
    foreach($modulesDir as $moduleDir) {
        if (!$moduleDir->isDot() &&
                is_dir($moduleDir->getPathname() . '/views/js'))
        {
            $jsDir = new DirectoryIterator($moduleDir->getPathname() . '/views/js');
            foreach($jsDir as $jsFile) if ($jsFile->isFile()) {
                $jsFiles[] = $jsFile->getPathname();
            }
        }
    }
    $jsFiles[] = APPLICATION_PATH . '/layouts/backend/default/js/scripts.js';
    echo $this->jsHeadScripts($jsFiles, 'default', 'backend');
    ?>

</body>
</html>