<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5); ?>
<html lang="pt_BR">
<head>
    <?php
        $this->syncLayoutFiles('img', 'default');
        $this->headTitle('Meu site')->setSeparator(' - ');
        if (isset($this->content)) $this->headTitle()->prepend($this->content->title);
        echo $this->headTitle();

        $this->headMeta()->setCharset('UTF-8')
             ->appendName('keywords', isset($this->content) ? $this->content->keywords : 'framework, PHP, productivity')
             ->appendName('viewport', 'width=device-width, initial-scale=1.0')
             ->appendName('description', '')
             ->appendName('author', 'jaimeneto.com');
        echo $this->headMeta() . PHP_EOL;

        $themePath = APPLICATION_PATH . '/layouts/frontend/' . Acl_Model_Auth::getTheme();

        echo $this->cssHeadLinks(array(
            'lib/bootstrap/css/bootstrap.min.css',
            "{$themePath}/css/style.css",
            "{$themePath}/css/blocks.css"
        ));
    ?>
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-144-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-114-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-72-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-57-precomposed.png'); ?>">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('lib/bootstrap/ico/favicon.png'); ?>">
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            
            <?php echo $this->navbarHeader('MEU SITE', 'navbar-collapse-1', $this->baseUrl()); ?>

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                
                <?php echo $this->navbar(); ?>
                
                <div class="navbar-form navbar-right">
                    <a href="<?php echo $this->adminBaseUrl(); ?>" target="_blank">
                        Área administrativa
                    </a>
                </div>
                
            </div>
        </div>
    </nav>

    <main class="container-fluid">

        <?php echo $this->layout()->content; ?>

        <hr />

    </main>

    <footer class="text-center">
        <div class="container-fluid">
            <p>&copy; JAIMENETO.COM 2013</p>
        </div>
    </footer>
    
    <?php echo $this->jsHeadScripts(array(
        'lib/jquery/jquery-1.11.1.min.js',
        'lib/bootstrap/js/bootstrap.min.js'
    )); ?>
</body>
</html>
