<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5); ?>
<html lang="pt_BR">
<head>
    <?php
        $this->syncLayoutFiles('img', 'default');
        $this->headTitle('Meu site')->setSeparator(' - ');
        if (isset($this->content)) $this->headTitle()->prepend($this->content->title);
        echo $this->headTitle();

        $this->headMeta()->setCharset('UTF-8')
             ->appendName('keywords', 'framework, PHP, productivity')
             ->appendName('viewport', 'width=device-width, initial-scale=1.0')
             ->appendName('description', '')
             ->appendName('author', 'jaimeneto.com');
        echo $this->headMeta() . PHP_EOL;

        $themePath = APPLICATION_PATH . '/layouts/frontend/' . Acl_Model_Auth::getTheme();

        echo $this->cssHeadLinks(array(
            'lib/bootstrap/css/bootstrap.min.css',
            'lib/bootstrap/css/bootstrap-responsive.min.css',
            "{$themePath}/css/style.css",
            "{$themePath}/css/blocks.css"
        ));
    ?>
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-144-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-114-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-72-precomposed.png'); ?>">
    <link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl('lib/bootstrap/ico/apple-touch-icon-57-precomposed.png'); ?>">
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('lib/bootstrap/ico/favicon.png'); ?>">
</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="<?php echo $this->baseUrl(); ?>">MEU SITE</a>
                <div class="nav-collapse collapse">
                    <?php echo $this->showMenu(1, 'navbar.phtml'); ?>
                    <p class="navbar-text pull-right">
                        <a href="<?php echo $this->adminBaseUrl(); ?>" target="_blank">
                            Área administrativa
                        </a>
                    </p>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container-fluid">

        <?php echo $this->layout()->content; ?>

        <hr />

        <footer>
            <p>&copy; JAIMENETO.COM 2013</p>
        </footer>

    </div> <!-- /container -->

    <?php echo $this->jsHeadScripts(array(
        'lib/jquery/jquery-1.8.3.min.js',
        'lib/bootstrap/js/bootstrap.min.js'
    )); ?>
</body>
</html>
