<div class="control-group">
    <label for="meta-field-<?php echo $this->metafield->fieldname ?>-multiOptions"
           class="control-label">Opções</label>
    <div class="controls">
        <?
            $multiOptions = array();
            $metafieldMultiOptions = $this->metafield->getOption('multiOptions');
            if ($metafieldMultiOptions) {
                foreach($metafieldMultiOptions as $key => $option) {
                    $multiOptions[] = "{$key}:{$option}";
                }
            } else {
                $metafieldMultiOptions = array();
            }
            $multiOptions = implode(PHP_EOL, $multiOptions);
            echo $this->formTextarea("meta[field][{$this->metafield->fieldname}][multiOptions]",
                $multiOptions, array('class' => 'input-block-level multiOptions', 'rows' => 5));

//                if (!($this->metafield->hasOption('required') && $this->metafield->getOption('required'))) {
                $metafieldMultiOptions = array('' => '') + $metafieldMultiOptions;
//                }
        ?>
        <span class="help-block">
            <strong>Dica:</strong>
            Insira uma opção por linha, separando chave e valor com dois-pontos:
            chave:valor
        </span>
    </div>
</div>

<div class="control-group">
    <label for="meta-field-<?php echo $this->metafield->fieldname ?>-display"
           class="control-label">Exibição</label>
    <div class="controls">
        <?php echo $this->formSelect("meta[field][{$this->metafield->fieldname}][display]",
            $this->metafield->getOption('display') ? $this->metafield->getOption('display') : null,
            array('class' => 'input-block-level'), array(
                'select' => 'Exibir uma lista suspensa (drop down)',
                'list' => 'Todas as opções visíveis (radio / checkbox)')) ?>
    </div>
</div>

<div class="control-group">
    <div class="controls">
        <label for="meta-relationship-<?php echo $this->metafield->fieldname ?>-multiple" class="checkbox">
            <?php echo $this->formCheckbox("meta[field][{$this->metafield->fieldname}][multiple]", null,
                $this->metafield->getOption('multiple') ? array('checked' => 'checked') : '') ?>
            Permitir selecionar várias opções
        </label>
    </div>
</div>

<div class="control-group">
    <label for="meta-field-<?php echo $this->metafield->fieldname ?>-value"
           class="control-label">Valor padrão</label>
    <div class="controls">
        <?php echo $this->formSelect("meta[field][{$this->metafield->fieldname}][value]",
            $this->metafield->getOption('value') ? $this->metafield->getOption('value') : '',
            array('class' => 'input-block-level'), $metafieldMultiOptions) ?>
    </div>
</div>