<div class="control-group">
    <label for="meta-file-<?php echo $this->metafield->fieldname ?>-width"
           class="control-label">Largura padrão</label>
    <div class="controls">
        <div class="input-append">
            <?php echo $this->formText("meta[file][{$this->metafield->fieldname}][width]",
                $this->metafield->getOption('width'),
                array('class' => 'input-mini')) ?>
            <span class="add-on">px</span>
        </div>
    </div>
</div>

<div class="control-group">
    <label for="meta-file-<?php echo $this->metafield->fieldname ?>-height"
           class="control-label">Altura padrão</label>
    <div class="controls">
        <div class="input-append">
            <?php echo $this->formText("meta[file][{$this->metafield->fieldname}][height]",
                $this->metafield->getOption('height'),
                array('class' => 'input-mini')) ?>
            <span class="add-on">px</span>
        </div>
    </div>
</div>

<div class="control-group">
    <div class="controls">
        <label for="meta-file-<?php echo $this->metafield->fieldname ?>-multiple" class="checkbox">
            <?php echo $this->formCheckbox("meta[file][{$this->metafield->fieldname}][multiple]", null,
                    $this->metafield->getOption('multiple') ? array('checked' => 'checked') : '') ?>
            Permitir adicionar várias imagens
        </label>
    </div>

    <div class="controls">
        <label for="meta-file-<?php echo $this->metafield->fieldname ?>-sortable" class="checkbox">
            <?php echo $this->formCheckbox("meta[file][{$this->metafield->fieldname}][sortable]", null,
                    $this->metafield->getOption('sortable') ? array('checked' => 'checked') : '') ?>
            Permitir alterar a ordem das imagens
        </label>
    </div>
</div>