<div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse"
       data-parent="#accordion_relationships"
       href="#meta_fields_<?php echo $this->metafield->fieldname; ?>-element">
            <?php echo $this->metafield->getOption('label'); ?>

        <div class="pull-right fieldtype">
            <?php echo $this->metafield->getFieldtype(); ?>
        </div>
    </a>
</div>
<div id="meta_fields_<?php echo $this->metafield->fieldname; ?>-element"
     class="accordion-body collapse">
    <div class="accordion-inner form-horizontal">

        <div class="pull-right">
            <a href="#" class="remove-meta-field"
               id="meta-relationship-<?php echo $this->metafield->fieldname; ?>-remove"
                title="Excluir"><i class="icon-remove"></i></a>
        </div>

        <?php echo $this->formHidden("meta[relationship][{$this->metafield->fieldname}][type]",
            $this->metafield->getOption('type')); ?>

        <div class="control-group">
            <label for="meta_fields-<?php echo $this->metafield->fieldname; ?>-label"
                   class="control-label">Rótulo</label>
            <div class="controls">
                <?php
                    echo $this->formText("meta[relationship][{$this->metafield->fieldname}][label]",
                    $this->metafield->getOption('label'), array('class' => 'meta-fields-label'));
                ?>
            </div>

            <div class="controls">
                <label for="meta_fields-<?php echo $this->metafield->fieldname; ?>-required"
                       class="checkbox">
                    <?php echo $this->formCheckbox("meta[relationship][{$this->metafield->fieldname}][required]", null,
                            $this->metafield->getOption('required')
                            ? array('checked' => 'checked') : ''); ?>
                    Campo obrigatório
                </label>
            </div>
        </div>

        <?php echo $this->render("content-type/form/config/relationship-{$this->metafield->getOption('type')}.phtml"); ?>
    </div>
</div>