<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Conteúdo</h2>
        </div>
        <div class="panel-body">
            <ul class="list-unstyled">
                <?php
                foreach($this->contentTypes as $contentType):
                    $children = $contentType->getChildren();
                ?>
                <li>
                    <strong>
                        <a href="<?php echo $this->adminBaseUrl('content/content'
                            . '?filter[id_content_type]=' . $contentType->id); ?>">
                            <?php echo $this->escape($contentType->plural); ?>
                        </a>
                    </strong>

                    <span class="badge pull-right">
                        <?php echo $contentType->countContents(); ?>
                    </span>

                    <?php if($children): ?>
                    <ul>
                        <?php foreach($children as $childType): ?>
                        <li>
                            <strong>
                                <a href="<?php echo $this->adminBaseUrl('content/'
                                    . 'content?filter[id_content_type]='
                                    . $childType->id); ?>">
                                    <?php echo $this->escape($childType->plural); ?>
                                </a>
                            </strong>
                            <span class="badge badge-info pull-right">
                                <?php echo $childType->countContents(); ?>
                            </span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Usuários</h2>
        </div>
        <div class="panel-body">
            <ul class="list-unstyled">
                <?php foreach($this->roles as $role):
                if($role->id != 'guest'): ?>
                <li>
                    <strong><?php echo $this->escape($role->role); ?></strong>
                    <span class="badge badge-info pull-right">
                        <?php echo $role->countUsers(); ?>
                    </span>
                </li>
                <?php endif;
                endforeach; ?>
            </ul>
        </div>
    </div>
</div>

<div class="col-md-9">
    <div class="jumbotron">
        <h1>Bem vindo ao FrontZend!</h1>
        <p>
            Este é um sistema de gerencimento de conteúdo desenvolvido com foco na
            usabilidade, procurando tornar o trabalho, tanto dos desenvolvedores
            quanto dos usuários, mais fácil e intuitivo e totalmente flexível,
            aumentando a produtividade e tornando a tarefa de criar e manter
            sites mais objetiva e prazerosa.
        </p>
        <p><a class="btn btn-primary btn-lg" href="http://frontzend.jaimeneto.com">Saiba mais »</a></p>
    </div>
    <div class="row">
        <div class="col-md-4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-zf-lg.png'); ?>" />
            <p>
                Toda a estrutura do FrontZend foi feita usando como base o Zend Framework,
                o que permitiu deixá-la organizada, robusta e muito flexível. As funcionalidades
                foram divididas em módulos, e a criação de novos módulos, que se complementem às
                necessidades de cada site, é bastante simples.
            </p>
            <p><a href="http://www.zendframework.com/manual/1.12/en/manual.html" class="btn" target="_blank">zendframework.com »</a></p>
        </div>
        <div class="col-md-4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-bootstrap-lg.png'); ?>" />
            <p>
                Seguindo a tendência atual da internet, utilizamos o Bootstrap para
                a criação dos layouts feitos para o FrontZend, uma vez que ele simplifica 
                a construção de layouts para sites, além de permitir que sejam responsivos, 
                funcionando em diversas plataformas, seja smartphones, tablets, notebookes 
                ou desktops.
            </p>
            <p><a href="http://getbootstrap.com" class="btn" target="_blank">getbootstrap.com »</a></p>
        </div>
        <div class="col-md-4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-jquery-lg.png'); ?>" />
            <p>
                Devido a sua sintaxe simplificada, e seus diversos plugins disponíveis na
                internet, o jQuery já é tão popular entre os programadores
                que trabalham com web, que muitos mal conseguem pensar em criar um site
                utilizando javascript puro e o FrontZend utiliza diversos desses recursos.
            </p>
            <p>
                <a href="http://jquery.com" class="btn" target="_blank">jquery.com »</a>
                <a href="http://api.jqueryui.com/" class="btn" target="_blank">jqueryui.com »</a>
            </p>
        </div>
    </div>

</div>