<div class="span3">
    <div class="well">
        <h2>Conteúdo</h2>
        <ul class="unstyled">
            <?php
            foreach($this->contentTypes as $contentType):
                $children = $contentType->getChildren();
            ?>
            <li>
                <strong>
                    <a href="<?php echo $this->adminBaseUrl('content/content'
                        . '?filter[id_content_type]=' . $contentType->id); ?>">
                        <?php echo $this->escape($contentType->plural); ?>
                    </a>
                </strong>

                <span class="badge pull-right">
                    <?php echo $contentType->countContents(); ?>
                </span>

                <?php if($children): ?>
                <ul>
                    <?php foreach($children as $childType): ?>
                    <li>
                        <strong>
                            <a href="<?php echo $this->adminBaseUrl('content/'
                                . 'content?filter[id_content_type]='
                                . $childType->id); ?>">
                                <?php echo $this->escape($childType->plural); ?>
                            </a>
                        </strong>
                        <span class="badge badge-info pull-right">
                            <?php echo $childType->countContents(); ?>
                        </span>
                    </li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="well">
        <h2>Usuários</h2>
        <ul class="unstyled">
            <?php foreach($this->roles as $role):
            if($role->id != 'guest'): ?>
            <li>
                <strong><?php echo $this->escape($role->role); ?></strong>
                <span class="badge badge-info pull-right">
                    <?php echo $role->countUsers(); ?>
                </span>
            </li>
            <?php endif;
            endforeach; ?>
        </ul>
    </div>
</div>

<div class="span9">
    <div class="hero-unit">
        <h1>Bem vindo ao FrontZend!</h1>
        <p>
            Este é um sistema de gerencimento de conteúdo desenvolvido com foco na
            usabilidade, procurando tornar o trabalho, tanto dos desenvolvedores
            quanto dos usuários, mais fácil e intuitivo e totalmente flexível,
            aumentando a produtividade e tornando a tarefa de criar e manter
            sites mais objetiva e prazerosa.
        </p>
        <p><a class="btn btn-primary btn-large" href="http://frontzend.jaimeneto.com">Saiba mais »</a></p>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-zf.png'); ?>" />
            <br /><br />
            <p>
                Toda a estrutura do FrontZend foi feita usando como base o Zend Framework,
                o que permitiu deixá-la organizada, robusta e muito flexível. As funcionalidades
                foram divididas em módulos, e a criação de novos módulos, que se complementem às
                necessidades de cada site, é bastante simples.
            </p>
            <p><a href="http://www.zendframework.com/manual/1.12/en/manual.html" class="btn" target="_blank">zendframework.com »</a></p>
        </div>
        <div class="span4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-bootstrap.jpg'); ?>" />
            <br /><br />
            <p>
                Seguindo a tendência atual da internet, utilizamos o Twitter Bootstrap para
                a criação dos layouts feitos para o FrontZend, pois com ele, o é simples fazer
                um site fácil de dar manutenção e que funcione em diversas plataformas,
                seja celular, tablet ou desktop.
            </p>
            <p><a href="http://getbootstrap.com/2.3.2" class="btn" target="_blank">getbootstrap.com »</a></p>
        </div>
        <div class="span4">
            <img src="<?php echo $this->baseUrl('cache/layouts/backend/default/img/logo-jquery.png'); ?>" />
            <br /><br />
            <p>
                Devido a sua sintaxe simplificada, e seus diversos plugins disponíveis na
                internet, o jQuery já é tão popular entre os programadores
                que trabalham com web, que muitos mal conseguem pensar em criar um site
                utilizando javascript puro e o FrontZend utiliza diversos desses recursos.
            </p>
            <p>
                <a href="http://jquery.com" class="btn" target="_blank">jquery.com »</a>
                <a href="http://api.jqueryui.com/" class="btn" target="_blank">jqueryui.com »</a>
            </p>
        </div>
    </div>

</div>