<?php
/* AVAILABLE OPTIONS:
 *
 * types
 * limit
 * form_filter
 * search_result
 * load_related
 * template
 */

if($this->contents): ?>

    <div <?php echo $this->htmlTagAttribs($this->block, array('class' => 'block-content-contents-excerpt')); ?>>
        <?php if($this->block->getOption('form_filter')): ?>
        <fieldset>
            <legend>Busca avançada</legend>
            <?php echo $this->formFilter; ?>
        </fieldset>
        <?php endif; ?>

        <ul class="nav nav-pills nav-stacked">
            <?php foreach($this->contents as $content): ?>
            <li>
                <a href="<?php echo $this->baseUrl($content->slug); ?>">

                    <div class="pull-left">
                        <span class="label">
                            <?php echo $content->getDatePublished()->get('EEEE, dd / MM / yyyy'); ?>
                        </span>

                        <span class="label label-info">
                            <?php echo $this->escape($content->getType()->type); ?>
                        </span>
                    </div>

                    <h4><?php echo $this->escape($content->title); ?></h4>

                    <div class="image pull-<?php echo $this->cycle(array('left', 'right'))->next(); ?>">
                        <?php echo $this->contentImage($content, 'poster', 114, 160); ?>
                    </div>
                    
                    <div class="text">
                        <?php echo $content->excerpt
                            ? $content->excerpt
                            : $this->stringLength(strip_tags($content->text, '<p><br>'), 800) ?>
                    </div>

                    <br class="clear" />

                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>

<?php elseif($this->block->getOption('search_result')): ?>

    <p class="info">Nenhum resultado encontrado.</p>

<?php endif; ?>