<div class="form-group">
    <label for="meta-<?php echo $this->metafield->fieldname ?>-multiOptions"
           class="col-sm-2 control-label">Opções</label>
    <div class="col-sm-9">
        <?php
            $multiOptions = array();
            $metafieldMultiOptions = $this->metafield->getOption('multiOptions');
            if ($metafieldMultiOptions) {
                foreach($metafieldMultiOptions as $key => $option) {
                    $multiOptions[] = "{$key}:{$option}";
                }
            } else {
                $metafieldMultiOptions = array();
            }
            $multiOptions = implode(PHP_EOL, $multiOptions);
            echo $this->formTextarea("meta[{$this->metafield->fieldname}][multiOptions]",
                $multiOptions, array('class' => 'form-control multiOptions', 'rows' => 5));

//                if (!($this->metafield->hasOption('required') && $this->metafield->getOption('required'))) {
                $metafieldMultiOptions = array('' => '') + $metafieldMultiOptions;
//                }
        ?>
        <span class="help-block">
            <strong>Dica:</strong>
            Insira uma opção por linha, separando chave e valor com dois-pontos:
            chave:valor
        </span>
    </div>
</div>

<div class="form-group">
    <label for="meta-<?php echo $this->metafield->fieldname ?>-display"
           class="col-sm-2 control-label">Exibição</label>
    <div class="col-sm-9">
        <?php echo $this->formSelect("meta[{$this->metafield->fieldname}][display]",
            $this->metafield->getOption('display') ? $this->metafield->getOption('display') : null,
            array('class' => 'form-control'), array(
                'select' => 'Exibir uma lista suspensa (drop down)',
                'list' => 'Todas as opções visíveis (radio / checkbox)')) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-9">
        <div class="checkbox">
            <label for="meta-relationship-<?php echo $this->metafield->fieldname ?>-multiple">
                <?php echo $this->formCheckbox("meta[{$this->metafield->fieldname}][multiple]", null,
                    $this->metafield->getOption('multiple') ? array('checked' => 'checked') : ''); ?>
                Permitir selecionar várias opções
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    <label for="meta-<?php echo $this->metafield->fieldname ?>-value"
           class="col-sm-2 control-label">Valor padrão</label>
    <div class="col-sm-9">
        <?php echo $this->formSelect("meta[{$this->metafield->fieldname}][value]",
            $this->metafield->getOption('value') ? $this->metafield->getOption('value') : '',
            array('class' => 'form-control'), $metafieldMultiOptions) ?>
    </div>
</div>