<div class="row-fluid">

    <div class="span9">
        <ul class="sortable accordion unstyled" id="accordion_relationships">
            <?php
            $metafields = $this->contentType->getMetafields()->relationship;

            if($metafields):
                foreach($metafields as $metafield):
            ?>
            <li class="accordion-group">

                <?php echo $this->partial("content-type/form/config/relationship.phtml", array(
                    'metafield'  => $metafield,
                    'collapsed'  => true
                )); ?>

            </li>
            <?php
                endforeach;
            endif;
            ?>
        </ul>
    </div>

    <div class="span3">

        <fieldset>
            <legend>Adicionar novo relacionamento</legend>

            <div>
                <label for="add_meta_relationship_name">Identificação</label>
                <?php echo $this->formText('add_meta_relationship_name', '', array(
                    'placeholder' => 'Id do campo',
                    'class' => 'input-block-level'));
                ?>
            </div>

            <div>
                <label for="add_meta_relationship_type">Tipo de relacionamento</label>
                <?php echo $this->formRadio('add_meta_relationship_type', null,
                    array('label_class' => 'radio'),
                    Content_Model_Metafield::getFieldtypes('relationship'),
                    ''); ?>

                <div style="margin-top:20px;" class="btn-group">
                    <?php echo $this->formButton('add_meta_relationship_btn',
                        'Adicionar',
                        array('class' => 'btn btn-large btn-warning')); ?>
                    <?php echo $this->formReset('reset_meta_relationship_btn', 
                        'Limpar', array('class' => 'btn btn-large')); ?>
                </div>
            </div>

        </fieldset>

    </div>

</div>