<?php if ($this->images):
    $carouselId = 'content_images_carousel_' . $this->block->getOption('field');
?>
<div <?php echo $this->htmlTagAttribs($this->block, array('class' => 'block-content-images-carousel')); ?>>

    <div class="carousel slide" id="<?php echo $carouselId; ?>" data-ride="carousel">
    
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php for($i=0; $i < count($this->images); $i++): ?>
            <li data-target="#<?php echo $carouselId; ?>"
                data-slide-to="<?php echo $i; ?>"
                <?php echo $i == 0 ? ' class="active"' : ''; ?>></li>
            <?php endfor; ?>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $first=true; foreach($this->images as $image): ?>
            <div class="item<?php echo $first ? ' active' : ''; ?>">
                <img src="<?php echo $image; ?>" alt="" class="center-block" />
            </div>
            <?php $first=false; endforeach; ?>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#<?php echo $carouselId; ?>"
            role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">&lsaquo;</span>
        </a>
        <a class="right carousel-control" href="#<?php echo $carouselId; ?>"
            role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">&rsaquo;</span>
        </a>

    </div>
        
</div>
<?php endif; ?>