<?php if ($this->images):
    $carouselId = 'content_images_carousel_' . $this->block->getOption('image');
?>
<div id="<?php echo $carouselId; ?>" class="block block-content-images
     block-content-images-carousel carousel slide
     <?php echo $this->cssVisibility($this->block); ?>">

    <ol class="carousel-indicators">
        <?php for($i=0; $i < count($this->images); $i++): ?>
        <li data-target="#<?php echo $carouselId; ?>"
            data-slide-to="<?php echo $i; ?>"
            <?php echo $i == 0 ? ' class="active"' : ''; ?>></li>
        <?php endfor; ?>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner">
        <?php $first=true; foreach($this->images as $image): ?>
        <div class="<?php echo $first ? 'active ' : ''; ?>item">
            <img src="<?php echo $image; ?>" width="100%" alt="" />
        </div>
        <?php $first=false; endforeach; ?>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#<?php echo $carouselId; ?>"
       data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#<?php echo $carouselId; ?>"
       data-slide="next">&rsaquo;</a>

</div>
<?php endif; ?>