<?php if ($this->images): ?>
<div <?php echo $this->htmlTagAttribs($this->block, array('class' => 'block-content-images-thumbnails')); ?>>

    <div class="row">
        <?php foreach($this->images as $image): ?>
        <div class="col-xs-6 col-md-3">
            <a href="<?php echo $image; ?>" class="thumbnail" target="_blank">
                <img src="<?php echo $image; ?>" alt="" />
            </a>
        </div>
        <?php endforeach; ?>
    </div>

</div>
<?php endif; ?>