<?php 
$status = array(
    'A' => 'Ativo',
    'I' => 'Inativo',
    'D' => 'Excluído',
);
$statusIcon = array(
    'A' => 'glyphicon glyphicon-eye-open',
    'I' => 'glyphicon glyphicon-eye-close',
    'D' => 'glyphicon glyphicon-remove-circle',
);
$rowClass = array(
    'A' => '',
    'I' => ' class="warning"',
    'D' => ' class="error"',
);
?>

<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Comentários</small>
    </h1>
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Comentários cadastrados</h3>
    </div>
    
    <div class="panel-body">
        <div id="filters">
            <?php echo $this->form; ?>
        </div>        
    </div>

    <div class="table-horizontal">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th class="hidden-xs hidden-sm">Id</th>
                    <th>Nome</th>
                    <th class="hidden-xs hidden-sm">Tipo</th>
                    <th class="hidden-xs hidden-sm">Conteúdo</th>
                    <th>Comentários</th>
                    <th style="display:none">Status</th>
                    <th class="span1">Alteração</th>
                    <th width="50"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $comment): ?>
                    <tr<?php echo $rowClass[$comment->status]; ?>>
                        <td title="<?php echo $comment->id; ?>" class="hidden-xs hidden-sm">
                            <?php echo $comment->id; ?>
                        </td>
                        <td title="<?php echo $this->escape($comment->name); ?>">
                            <?php echo $this->escape($comment->name); ?>
                        </td>
                        <td title="<?php echo $this->escape($comment->getContent()->getType()->type); ?>" class="hidden-xs hidden-sm">
                            <?php echo $this->escape($comment->getContent()->getType()->type); ?>
                        </td>
                        <td style="max-width: 200px" title="<?php echo $this->escape($comment->getContent()->title); ?>" class="hidden-xs hidden-sm">
                            <?php echo $this->escape($comment->getContent()->title); ?>
                        </td>
                        <td title="<?php echo $this->escape($comment->comments); ?>">
                            <?php echo $this->escape($comment->comments); ?>
                        </td>
                        <td title="<?php echo $status[$comment->status]; ?>" style="display:none">
                            <?php echo $status[$comment->status]; ?>
                        </td>
                        <td title="<?php echo $comment->getDateUpdated()->get('dd/MM/yyyy HH:mm:ss'); ?>">
                            <span class="visible-md visible-lg"><?php echo $comment->getDateUpdated()->get('dd/MM/yy HH:mm') ?></span>
                            <span class="hidden-md hidden-lg"><?php echo $comment->getDateUpdated()->get('dd/MM/yy') ?></span>
                        </td>
                        <td class="actions">
                            <a href="#" title="<?php echo $status[$comment->status] ?>"
                               rel="tooltip"><span class="<?php echo $statusIcon[$comment->status] ?>"></span></a>

                            <a href="mailto:<?php echo $this->escape($comment->email); ?>"
                               title="<?php echo $this->escape($comment->email); ?>"
                               target="_blank" rel="tooltip"><span class="glyphicon glyphicon-envelope"></span></a>

                            <a href="<?php echo $this->adminBaseUrl('content/comment/remove'); ?>"
                               title="Enviar para a lixeira" rel="tooltip"><span class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="8" class="text-center">
                        Exibindo <?php echo $this->paginator->getCurrentItemCount(); ?> de
                        <?php echo $this->paginator->getTotalItemCount(); ?> itens cadastrados
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
        
    <div class="panel-body"><?php echo $this->paginator; ?></div>
</div>