<div class="row thumbnails">
    <?php foreach($this->files as $image): ?>
    <div class="col-xs-6 col-md-3">
        <a href="#<?php echo $image->id; ?>" class="thumbnail"
           rel="<?php echo $image->path; ?>">
            <img src="<?php echo $this->thumb($image, 150, 150, true); ?>"
                 alt="<?php echo $this->escape($image->original_name); ?>" />
        </a>
    </div>
    <?php endforeach; ?>
</div>