<div class="page-header">
    <?php
        $displayGroups = $this->form->getDisplayGroups();
        if($displayGroups):
    ?>
    <ul class="nav nav-pills pull-right">
        <?php foreach($displayGroups as $displayGroup): ?>
        <?php if($displayGroup->getLegend()): ?>
        <li<?php echo $displayGroup->getName() == 'main_elements' ? ' class="active"' : ''; ?>>
            <a href="#<?php echo $displayGroup->getName(); ?>" data-toggle="tab">
                <?php echo $displayGroup->getLegend(); ?>
            </a>
        </li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    
    <h1>
        <span class="glyphicon glyphicon-image"></span> 
        Arquivos
        <small>Imagens</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="row">

    <form id="<?php echo $this->form->getAttrib('id'); ?>"
        action="<?php echo $this->form->getAction(); ?>"
        method="<?php echo $this->form->getMethod(); ?>"
        class="<?php echo $this->form->getAttrib('class'); ?>"
        enctype="<?php echo $this->form->getAttrib('enctype'); ?>">

                <?php foreach($this->form->getDisplayGroups() as $displayGroup): ?>
                <div id="<?php echo $displayGroup->getName(); ?>" class="tab-pane
                    <?php echo $displayGroup->getName() == 'main_elements' ? ' active' : 'form-horizontal'; ?>">

                    <?php if ($displayGroup->getName() == 'main_elements' &&
                              $this->form->getElement('id_file')->getValue()): ?>

                    <div class="col-sm-4">
                        <div class="panel panel-default">
                            <div class="panel-body">

                                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="heading_image_data">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#image_data" aria-expanded="true" aria-controls="image_data">
                                                    Dados da imagem
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="image_data" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_image_data">
                                            <div class="panel-body">
                                                <?php foreach($displayGroup->getElements() as $element):
                                                    echo $element;
                                                    if ($element->getName() == 'credits'): ?>
                                                        <div class="checkbox">
                                                            <label for="modify-write">
                                                                <?php echo $this->formCheckbox('modify[write]'); ?>
                                                                Exibir marca d'água
                                                            </label>
                                                        </div>
                                                    <?php endif;
                                                endforeach; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="heading_image_filters">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#image_filters" aria-expanded="true" aria-controls="image_filters">
                                                    Filtros
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="image_filters" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_image_filters">
                                            <div class="panel-body">
                                                <div class="checkbox">
                                                    <label for="modify-flip-v">
                                                        <?php echo $this->formCheckbox('modify[flip][v]'); ?>
                                                        Inverter na vertical
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-flip-h">
                                                        <?php echo $this->formCheckbox('modify[flip][h]'); ?>
                                                        Inverter na horizontal
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-effect-drawing">
                                                        <?php echo $this->formCheckbox('modify[effect][drawing]'); ?>
                                                        Desenho
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-effect-sepia">
                                                        <?php echo $this->formCheckbox('modify[effect][sepia]'); ?>
                                                        Sépia
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-filter-negate">
                                                        <?php echo $this->formCheckbox('modify[filter][negate]'); ?>
                                                        Negativo
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-filter-grayscale">
                                                        <?php echo $this->formCheckbox('modify[filter][grayscale]'); ?>
                                                        Escala de cinza
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-filter-smooth">
                                                        <?php echo $this->formCheckbox('modify[filter][smooth]'); ?>
                                                        Suavizar
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-filter-emboss">
                                                        <?php echo $this->formCheckbox('modify[filter][emboss]'); ?>
                                                        Realçar
                                                    </label>
                                                </div>

                                                <div class="checkbox">
                                                    <label for="modify-filter-edgedetect">
                                                        <?php echo $this->formCheckbox('modify[filter][edgedetect]'); ?>
                                                        Destacar bordas
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="heading_image_adjustments">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#image_adjustments" aria-expanded="true" aria-controls="image_adjustments">
                                                    Ajustes
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="image_adjustments" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_image_adjustments">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <label for="modify-filter-brightness">Iluminação</label>
                                                    <?php $multiOptions = array();
                                                    for($i = -255; $i <= 255; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][brightness]', 0,
                                                        array('class' => 'form-control'), $multiOptions); ?>
                                                </div>                   

                                                <div class="form-group">
                                                    <label for="modify-filter-contrast">Contraste</label>
                                                    <?php $multiOptions = array();
                                                    for($i = -100; $i <= 100; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][contrast]', 0,
                                                        array('class' => 'form-control'), $multiOptions); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label for="modify-filter-gaussian-blur">Borrar</label>
                                                    <?php $multiOptions = array();
                                                    for($i = 0; $i <= 100; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][gaussian-blur]', 0,
                                                        array('class' => 'form-control'), $multiOptions); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label for="modify-filter-selective-blur">Desfocar</label>
                                                    <?php $multiOptions = array();
                                                    for($i = 0; $i <= 100; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][selective-blur]', 0,
                                                        array('class' => 'form-control'), $multiOptions); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label for="modify-filter-mean-removal">Esboço</label>
                                                    <?php $multiOptions = array();
                                                    for($i = 0; $i <= 10; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][mean-removal]', 0,
                                                    array('class' => 'form-control'), $multiOptions); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label for="modify-filter-pixelate">Pontilhar</label>
                                                    <?php $multiOptions = array();
                                                    for($i = 0; $i <= 10; $i++) $multiOptions[$i] = $i;
                                                    echo $this->formSelect('modify[filter][pixelate]', 0,
                                                        array('class' => 'form-control'), $multiOptions); ?>
                                                </div>

                                                <div class="form-group">
                                                    <label for="modify-filter-colorize">Ajuste de cores (RGBA)</label>
                                                    <div class="filter-colorize">
                                                        <?php $multiOptions = array();
                                                        for($i = -255; $i <= 255; $i++) $multiOptions[$i] = $i; ?>

                                                        <?php echo $this->formSelect('modify[filter][colorize][red]', 0,
                                                            array('class' => 'form-control'), $multiOptions) . ' ';

                                                        echo $this->formSelect('modify[filter][colorize][green]', 0,
                                                            array('class' => 'form-control'), $multiOptions) . ' ';

                                                        echo $this->formSelect('modify[filter][colorize][blue]', 0,
                                                            array('class' => 'form-control'), $multiOptions) . ' ';

                                                        $multiOptions = array();
                                                        for($i = 0; $i <= 127; $i++) $multiOptions[$i] = $i;
                                                        echo $this->formSelect('modify[filter][colorize][alpha]', 0,
                                                            array('class' => 'form-control'), $multiOptions);
                                                        ?>
                                                    </div>
                                                </div><!--.form-group -->
                                            </div><!--.panel-body -->
                                        </div><!--.panel-collapse -->
                                    </div><!--.panel -->

                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="heading_image_resize">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#image_resize" aria-expanded="true" aria-controls="image_resize">
                                                    Redimensionar
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="image_resize" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading_image_resize">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <div class="col-sm-5">
                                                        <?php echo $this->formText('modify[resize][width]', 
                                                            null, array('class' => 'form-control', 'placeholder' => 'Largura')); ?>
                                                    </div>
                                                    <div class="col-sm-1 text-center">x</div>
                                                    <div class="col-sm-5">
                                                        <?php echo $this->formText('modify[resize][height]', 
                                                            null, array('class' => 'form-control', 'placeholder' => 'Altura')); ?>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="checkbox">
                                                        <label for="modify-resize-avatar">
                                                            <?php echo $this->formRadio('modify[resize][option]', 'auto', null, array(
                                                                'auto'    => 'Manter proporções',
                                                                'distort' => 'Preencher espaços (distorcer)',
                                                                'avatar'  => 'Preencher espaços (cortar)',
                                                                'fill'    => 'Preencher espaços com branco'
                                                            )); ?>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <?php echo $this->formReset('revert_original', 
                                'Reverter alterações',
                                array('class' => 'btn btn-warning col-sm-12')); ?>

                            </div><!--.panel-body -->

                            <div class="panel-footer text-center">
                                <?php echo $this->form->getElement('save')->setDecorators(array('ViewHelper')); ?>
                                <?php echo $this->form->getElement('apply')->setDecorators(array('ViewHelper')); ?>
                                <?php echo $this->form->getElement('cancel')->setDecorators(array('ViewHelper')); ?>
                            </div>
                        </div><!--.panel -->
                    </div>

                    <div class="col-sm-8" id="image_preview">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="btn-group pull-right" data-toggle="buttons">
                                    <label class="btn btn-default">
                                        <input type="checkbox" autocomplete="off" id="toggle_original"> Ver original
                                    </label>
                                </div>
                                <h3 class="panel-title">Editar imagem</h3>
                            </div>

                            <div class="panel-body text-center" id="modified_image">
                                <img src="<?php echo $this->baseUrl($this->file->getPath()); ?>"
                                 alt="<?php echo $this->escape($this->file->original_name) ?>" />
                                <div class="size">Dimensões: 
                                    <span class="width"><?php echo $this->file->getImageSize()->width; ?></span>
                                    x <span class="height"><?php echo $this->file->getImageSize()->height; ?></span>
                                </div>
                            </div><!--.panel-body -->

                            <div class="panel-body text-center" id="original_image" style="display:none">
                                <img src="<?php echo $this->baseUrl($this->file->getPath()); ?>"
                                 alt="<?php echo $this->escape($this->file->original_name) ?>" />
                                <div class="size">Dimensões: 
                                    <span class="width"><?php echo $this->file->getImageSize()->width; ?></span>
                                    x <span class="height"><?php echo $this->file->getImageSize()->height; ?></span>
                                </div>
                            </div><!--.panel-body -->

                        </div><!--.panel -->
                    </div>

                    <?php else: ?>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Informações</h3>
                        </div>
                        <div class="panel-body">
                            <?php foreach($displayGroup->getElements() as $element): ?>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label"><?php echo $element->getLabel(); ?></label>
                                    <div class="col-sm-10">
                                        <?php echo $element->setDecorators(array('ViewHelper')); ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <?php endif; ?>
                </div><!-- .tab-pane -->
                <?php endforeach; ?>

            </form>

        </div>

    </div>

</div>