<fieldset>
    <legend>Gerenciamento de Imagens</legend>

    <?php echo $this->alerts(); ?>

    <div class="span3 well sidebar-nav" id="dirs">
        <?php echo $this->navigation($this->dirs)->menu()->setUlClass('nav nav-list treeview'); ?>
    </div><!--/span-->

    <div class="span9" id="files">

        <ul class="thumbnails">
            <?php foreach($this->files as $image): ?>
            <li class="span2">
                <a href="<?php echo $this->adminBaseUrl('media/image/edit/id/'
                    . $image->id); ?>" class="thumbnail">
                    <img src="<?php echo $this->thumb($image, 150, 150, true); ?>"
                         alt="<?php echo $this->escape($image->original_name); ?>" />
                </a>
            </li>
            <?php endforeach; ?>
        </ul>

    </div>

</fieldset>