<?php $status = array(
    'A' => array('title' => 'Ativo', 'icon'  => 'glyphicon glyphicon-eye-open'),
    'I' => array('title' => 'Inativo', 'icon'  => 'glyphicon glyphicon-eye-close'),
    'D' => array('title' => 'Excluído', 'icon'  => 'glyphicon glyphicon-remove-circle'),
    'L' => array('title' => 'Trancado', 'icon'  => 'glyphicon glyphicon-lock')); 
?>

<div class="page-header">
    <h1>
        <div class="btn-group pull-right">
            <a class="btn btn-default" href="<?php echo $this->baseUrl($this->content->slug); ?>" target="_blank">
                <span class="glyphicon glyphicon-globe"></span> Visualizar
            </a>
        </div>
            
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Itens</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Excluir item</h3>
    </div>
    <div class="panel-body">
        <h4>
            <?php echo $this->escape($this->content->title); ?>
            <span class="label label-info"><?php echo $this->escape($this->content->getContentType()->type); ?></span>
            <span class="<?php echo $status[$this->content->status]['icon']; ?>"
               title="<?php echo $status[$this->content->status]['title']; ?>"></span>
        </h4>
        <span class="label"><?php echo ucfirst($this->content->getDatePublished()->get("EEEE, dd 'de' MM 'de' yyyy 'às' HH:mm")); ?></span>
        <span class="label label-important">Cadastrado por <?php echo $this->escape($this->content->getUser()->display_name); ?></span>
        <p><?php echo $this->content->excerpt
            ? $this->content->excerpt
            : $this->stringLength(strip_tags($this->content->text, '<p><br>'), 800) ?>
        </p>
    </div>

    <div class="panel-footer">
        <p><strong>Confirma a exclusão deste item?</strong></p>

        <form action="<?php echo $this->url(array('action' => 'remove')); ?>" 
              class="form-actions" method="post">
            <input type="hidden" name="id" value="<?php echo $this->content->id; ?>" />
            <?php if($this->content->status != 'D'): ?>
            <input type="submit" name="trash" value="Enviar para a lixeira" class="btn btn-warning btn-lg" />
            <?php endif; ?>
            <?php if($this->content->status == 'D'): ?>
            <input type="submit" name="restore" value="Restaurar" class="btn btn-primary btn-lg" />
            <input type="submit" name="delete" value="Excluir definitivamente" class="btn btn-danger btn-lg" />
            <?php endif; ?>
            <input type="submit" name="cancel" value="Cancelar" class="btn btn-default btn-lg" />
        </form>
    </div>
</div>