<style type="text/css">
.block-content-rating {
    margin: 10px 0;
}
.block-content-rating .label {
    cursor: default;
}
</style>

<div <?php echo $this->htmlTagAttribs($this->block); ?>>
    <div class="rating">
        <span class="rating-stars">
            <?php foreach($this->multiOptions as $rating => $ratingDescription): ?>
                <span class="glyphicon <?php echo ($rating <= $this->contentRating) ? 'glyphicon-star': 'glyphicon-star-empty'; ?>"
                     ><?php //echo $rating; ?></span>
            <?php endforeach; ?>
        </span>

        <span class="rating-description label label-default" title="<?php echo $this->multiOptions[$this->contentRating]; ?>"
              ><?php echo isset($this->multiOptions[$this->contentRating])
                  ? $this->multiOptions[$this->contentRating] : '';
        ?></span>
    </div>

    <?php /*if($this->userRating): ?>
    <div class="your-rating" title="<?php echo $this->multiOptions[$this->userRating->description] ?>">
        <div class="your-rating-label">Sua avaliação: </div>
        <?php foreach($this->multiOptions as $rating => $ratingDescription): ?>
            <a class="<?php echo ($rating <= $this->userRating->description)
                ? 'star-full': 'star-empty' ?>"><?php echo $rating ?></a>
        <?php endforeach ?>
        <span class="rating-description" title="<?php echo $this->multiOptions[$this->userRating->description] ?>"
              ><?php echo isset($this->multiOptions[$this->userRating->description])
                    ? $this->multiOptions[$this->contentRating] : '' ?></span>
        <br class="clear" />
    </div>
    <?php endif; */ ?>
</div>