<?php
$field = $this->block->getOption('field');
$contentUsers = $this->content->getUsers($field);
if($contentUsers):
?>
<div <?php echo $this->htmlTagAttribs($this->block); ?>>
    <?php 
    foreach($contentUsers as $contentUser):
        $user = $contentUser->getUser(); ?>
        <a href="<?php echo $this->baseUrl('u/' . $user->username); ?>"
           class="label label-default">
            <?php echo $this->escape($user->display_name); ?>
        </a>
    <?php endforeach; ?>
</div>
<?php endif; ?>