<?php
$field = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube->value): ?>

<style type="text/css">
.block-content-youtube a.youtube-link {
    cursor: pointer;
}
.block-content-youtube a.youtube-link img,
.block-content-youtube a.youtube-link .image-play {
    margin-top: 5px;
}
.block-content-youtube a.youtube-link .image-play {
    position: absolute;
    width: 210px;
    height: 157px;
    background: url(<?php echo $this->baseUrl('img/play.png'); ?>) no-repeat center center;
}
</style>


<div class="block block-content-youtube <?php echo $this->cssVisibility($this->block); ?>"
     id="content_<?php echo $field; ?>">

    <?php if(in_array($this->block->getOption('display'), array('dialog','youtube'))): ?>

    <a href="#<?php echo $this->escape($youtube->value); ?>"
       <?php echo $this->block->getOption('display') == 'dialog'
           ? 'class="youtube-link"'
           : 'target="_blank"'?>>
        <div class="image-play"></div>
        <?php echo $this->youtubeThumb($youtube->value); ?>
    </a>

    <?php 
        else /*if($this->block->getOption('display') == 'screen')*/:
            echo $this->youtubeVideo($youtube->value, 640, 390);
        endif;
    ?>
</div>
<?php endif; ?>