<div class="form-group">
    <label for="meta-<?php echo $this->metafield->fieldname ?>-width"
           class="col-sm-2 control-label">Largura padrão</label>
    <div class="col-sm-3">
        <div class="input-group">
            <?php echo $this->formText("meta[{$this->metafield->fieldname}][width]",
                $this->metafield->getOption('width'), array('class' => 'form-control')) ?>
            <span class="input-group-addon">px</span>
        </div>
    </div>

    <label for="meta-<?php echo $this->metafield->fieldname ?>-height"
           class="col-sm-2 control-label">Altura padrão</label>
    <div class="col-sm-3">
        <div class="input-group">
            <?php echo $this->formText("meta[{$this->metafield->fieldname}][height]",
                $this->metafield->getOption('height'), array('class' => 'form-control')) ?>
            <span class="input-group-addon">px</span>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-9">
        <div class="checkbox">
            <label for="meta-<?php echo $this->metafield->fieldname ?>-multiple">
                <?php echo $this->formCheckbox("meta[{$this->metafield->fieldname}][multiple]", null,
                        $this->metafield->getOption('multiple') ? array('checked' => 'checked') : '') ?>
                Permitir adicionar várias imagens
            </label>
        </div>

        <div class="checkbox">
            <label for="meta-<?php echo $this->metafield->fieldname ?>-sortable">
                <?php echo $this->formCheckbox("meta[{$this->metafield->fieldname}][sortable]", null,
                        $this->metafield->getOption('sortable') ? array('checked' => 'checked') : '') ?>
                Permitir alterar a ordem das imagens
            </label>
        </div>
    </div>
</div>