<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-th-large"></span> 
        Layout
        <small>Editor de layout</small>
    </h1>
</div>

<?php echo $this->alerts(); ?>

<div class="row">
    <div class="col-sm-3">
        <div class="panel panel-default sidebar-nav" id="layouts">
            <?php echo $this->navigation($this->tree)->menu()->setUlClass('nav nav-list treeview'); ?>
        </div>
    </div>

    <div class="col-sm-9">
        <?php 
        if ($this->form):
        $code = $this->form->getElement('code'); 
        $code->setDecorators(array('ViewHelper')); ?>
        <div class="panel panel-default sidebar-nav" id="files">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escape($code->getLabel()); ?></h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>