<?php
$multiOptions = FrontZend_Container::get('ContentType')->fetchPairs('plural');
?>

<div class="form-group">
    <label for="meta-relationship-<?php echo $this->metafield->fieldname; ?>-related"
           class="col-sm-2 control-label">Relacionado com</label>
    <div class="col-sm-9">
        <?php
            echo $this->formSelect("meta[{$this->metafield->fieldname}][related]",
            $this->metafield->getOption('related'),
            array('class' => 'form-control'), $multiOptions);
        ?>
    </div>
</div>

<div class="form-group">
    <label for="meta-relationship-<?php echo $this->metafield->fieldname; ?>-display"
           class="col-sm-2 control-label">Exibição</label>
    <div class="col-sm-9">
        <?php
            echo $this->formSelect("meta[{$this->metafield->fieldname}][display]",
                $this->metafield->getOption('display'), 
                array('class' => 'form-control'), 
                array('list' => 'Exibir a lista de opções',
                    'search' => 'Exibir um campo de busca'));
        ?>
    </div>
</div>
    
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-9">
        <div class="checkbox">
            <label for="meta-relationship-<?php echo $this->metafield->fieldname; ?>-multiple">
                <?php echo $this->formCheckbox("meta[{$this->metafield->fieldname}][multiple]", null,
                        $this->metafield->getOption('multiple')
                        ? array('checked' => 'checked', ) : ''); ?>
                Permitir selecionar várias opções
            </label>
        </div>
    </div>
</div>