<?php
/* AVAILABLE OPTIONS:
 *
 * types
 * limit
 * form_filter
 * search_result
 * template
 */

if($this->contents): ?>

<style type="text/css">
.block-content-contents-default ul li a {
    padding: 5px;
    color: #333;
}
.block-content-contents-default ul li a .label {
    text-transform: capitalize;
}
.block-content-contents-default ul li a .title {
    padding-top: 5px;
    font-weight: bold;
}
</style>

    <div <?php echo $this->htmlTagAttribs($this->block, array('class' => 'block-content-contents-titles')); ?>>
        <?php if($this->block->getOption('form_filter')): ?>
        <fieldset>
            <legend>Busca avançada</legend>
            <?php echo $this->formFilter; ?>
        </fieldset>
        <?php endif; ?>

        <ul class="nav nav-pills nav-stacked">
            <?php foreach($this->contents as $content): ?>
            <li>
                <a href="<?php echo $this->baseUrl($content->slug); ?>">
                    <div class="title">
                        <?php echo $this->escape($content->title); ?>
                    </div>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>

<?php elseif($this->options->search_result): ?>

    <p class="info">Nenhum resultado encontrado.</p>

<?php endif; ?>