<?php
$order = $this->form->getElement('order')->getValue();
$orderDesc = strpos($order, ' desc') > 0;
$order = str_replace(' desc', '', $order);

$status = array(
    'A' => 'Ativo',
    'I' => 'Inativo',
    'B' => 'Bloqueado',
    'D' => 'Excluído',
);
$statusIcon = array(
    'A' => 'glyphicon glyphicon-ok',
    'I' => 'glyphicon glyphicon-remove-circle',
    'B' => 'glyphicon glyphicon-ban-circle',
    'D' => 'glyphicon glyphicon-trash',
);
$rowClass = array(
    'A' => '',
    'I' => ' class="warning"',
    'B' => ' class="info"',
    'D' => ' class="danger"'
);
?>
<div class="page-header">
    <div class="btn-group pull-right">
      <a class="btn btn-default" href="<?php echo $this->adminBaseUrl('acl/user/add') ?>">
          <span class="glyphicon glyphicon-plus"></span> Cadastrar
      </a>
    </div>
    <h1>
        <span class="glyphicon glyphicon-lock"></span> 
        Acesso
        <small>Usuários</small>
    </h1>
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Usuários cadastrados</h3>
    </div>
    
    <div class="panel-body">
        <div id="filters">
            <?php echo $this->form; ?>
        </div>        
    </div>
    
    <div class="table-horizontal">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th<?php echo $order=='id_user' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/id_user' . ($order=='id_user' && !$orderDesc ? '+desc' : '')); ?>">
                            Id
                            <?php echo $order == 'id_user' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th  class="hidden-sm hidden-xs<?php echo $order=='username' ? ($orderDesc ? ' dropup' : ' dropdown') : ''; ?>">
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/username' . ($order=='username' && !$orderDesc ? '+desc' : '')); ?>">
                            Nome de usuário
                            <?php echo $order == 'username' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th<?php echo $order=='display_name' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/display_name' . ($order=='display_name' && !$orderDesc ? '+desc' : '')); ?>">
                            Nome de exibição
                            <?php echo $order == 'display_name' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th class="hidden-sm hidden-xs<?php echo $order=='name' ? ($orderDesc ? ' dropup' : ' dropdown') : ''; ?>">
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/name' . ($order=='name' && !$orderDesc ? '+desc' : '')); ?>">
                            Nome
                            <?php echo $order == 'name' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th<?php echo $order=='id_role' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/id_role' . ($order=='id_role' && !$orderDesc ? '+desc' : '')); ?>">
                            Função
                            <?php echo $order == 'id_role' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th class="col-md-1<?php echo $order=='dt_registered' ? ($orderDesc ? ' dropup' : ' dropdown') : ''; ?>">
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/dt_registered' . ($order=='dt_registered' && !$orderDesc ? '+desc' : '')); ?>">
                            Cadastro
                            <?php echo $order == 'dt_registered' ? '<span class="caret"></span>' : '' ?>
                        </a>
                    </th>
                    <th class="col-md-1<?php echo $order=='dt_lastaccess' ? ($orderDesc ? ' dropup' : ' dropdown') : ''; ?>">
                        <a href="<?php echo $this->adminBaseUrl('acl/user/list/order/dt_lastaccess' . ($order=='dt_lastaccess' && !$orderDesc ? '+desc' : '')); ?>">
                            <span class="visible-md visible-lg">Último acesso</span>
                            <span class="hidden-md hidden-lg">Acesso</span>
                            <?php echo $order == 'dt_lastaccess' ? '<span class="caret"></span>' : '' ?>
                        </a>
                    </th>
                    <th width="50"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $user): ?>
                    <tr<?php echo $rowClass[$user->status]; ?>>
                        <td title="<?php echo $user->id; ?>">
                            <?php echo $user->id; ?>
                        </td>
                        <td title="<?php echo $user->username; ?>" class="hidden-sm hidden-xs">
                            <?php echo $this->escape($user->username); ?>
                        </td>
                        <td title="<?php echo $user->display_name; ?>">
                            <?php echo $this->escape($user->display_name); ?>
                        </td>
                        <td title="<?php echo $user->name; ?>" class="hidden-sm hidden-xs">
                            <?php echo $this->escape($user->name); ?>
                        </td>
                        <td title="<?php echo $user->getRole()->role; ?>">
                            <?php echo $this->escape($user->getRole()->role); ?>
                        </td>
                        <td title="<?php echo $user->getDateRegistered()->get('dd/MM/yyyy HH:mm'); ?>">
                            <span class="visible-md visible-lg"><?php echo $user->getDateRegistered()->get('dd/MM/yyyy HH:mm'); ?></span>
                            <span class="hidden-md hidden-lg"><?php echo $user->getDateRegistered()->get('dd/MM/yyyy'); ?></span>
                        </td>
                        <?php $lastAccess = $user->dt_lastaccess
                            ? $user->getLastAccess()->get('dd/MM/yyyy HH:mm')
                            : 'nunca'; ?>
                        <td title="<?php echo $lastAccess; ?>">
                            <span class="visible-md visible-lg"><?php echo $lastAccess; ?></span>
                            <span class="hidden-md hidden-lg"><?php echo substr($lastAccess, 0, 10); ?></span>
                        </td>
                        <td class="actions">
                            <a href="#" title="<?php echo $status[$user->status]; ?>" rel="tooltip"
                               ><span class="<?php echo $statusIcon[$user->status]; ?>"></span></a>

                            <?php if($user->id == Zend_Auth::getInstance()->getIdentity()->id_user ||
                                $this->isAllowed('acl_user_edit')): ?>
                            <a href="<?php echo $this->adminBaseUrl("acl/user/edit/id/{$user->id}"); ?>"
                               title="Editar" rel="tooltip"><span class="glyphicon glyphicon-edit" title="Editar" rel="tooltip"></span></a>
                            <?php else: ?>
                                <span class="glyphicon glyphicon-edit" title="Editar" rel="tooltip"></span>
                            <?php endif; ?>

                            <?php if($user->id != Zend_Auth::getInstance()->getIdentity()->id_user &&
                                $this->isAllowed('acl_user_remove')): ?>
                            <a href="<?php echo $this->adminBaseUrl("acl/user/remove/id/{$user->id}"); ?>"
                               title="<?php echo $user->status == 'D' ? 'Excluir' : 'Enviar para a lixeira'; 
                               ?>" rel="tooltip"><span class="glyphicon glyphicon-<?php echo $user->status == 'D' 
                                       ? 'remove' : 'trash'; ?>"></span></a>
                            <?php else: ?>
                                <span class="glyphicon glyphicon-<?php echo $user->status == 'D' ? 'remove' : 'trash';
                                    ?> inactive"></span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="8" class="text-center">
                        Exibindo <?php echo $this->paginator->getCurrentItemCount(); ?> de
                        <?php echo $this->paginator->getTotalItemCount(); ?> usuários cadastrados
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
        
    <div class="panel-body"><?php echo $this->paginator; ?></div>
</div>