<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<div <?php echo $this->htmlTagAttribs($this->block, array(
    'class' => 'block-content-youtube-dialog', 'id' => 'content_' . $field)); ?>>

    <a href="#" data-toggle="modal" data-target="#<?php echo $this->escape($youtube->value); ?>">
        <?php echo $this->youtubeThumb($youtube->value); ?>
    </a>

    <!-- Modal -->
    <div class="modal fade" id="<?php echo $this->escape($youtube->value); ?>" 
         tabindex="-1" role="dialog" aria-labelledby="<?php echo $this->escape($youtube->value); ?>_label" 
         aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="<?php echo $this->escape($youtube->value); ?>_label">
                <?php echo $this->escape($this->content->title); ?>
            </h4>
          </div>
          <div class="modal-body">
            <?php echo $this->youtubeVideo($youtube->value, $width, $height, array('autoplay' => 1)); ?>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
          </div>
        </div>
      </div>
    </div>
    
</div>
<?php endif; ?>