<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<style type="text/css">
.block-content-youtube-link a {
    cursor: pointer;
    margin-top: 5px;
}
</style>

<div <?php echo $this->htmlTagAttribs($this->block, array(
    'class' => 'block-content-youtube-link', 'id' => 'content_' . $field)); ?>>

    <a href="http://www.youtube.com/watch?v=<?php echo $this->escape($youtube->value); ?>" target="_blank">
        <?php echo $this->youtubeThumb($youtube->value, $width, $height); ?>
    </a>

</div>
<?php endif; ?>