<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<div <?php echo $this->htmlTagAttribs($this->block, array(
    'class' => 'block-content-youtube-popup', 'id' => 'content_' . $field)); ?>>

    <a href="#" onclick="window.open('http://www.youtube.com/v/<?php echo $this->escape($youtube->value); 
        ?>', 'popup', 'width=<?php echo $width; ?>,height=<?php echo $height; ?>,scrollbars=no,status=1'); return false;">
        <?php echo $this->youtubeThumb($youtube->value, $width, $height); ?>
    </a>

</div>
<?php endif; ?>