<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<style type="text/css">
.block-content-youtube-link a {
    cursor: pointer;
    margin-top: 5px;
}
</style>

<div class="block block-content-youtube block-content-youtube-link <?php echo $this->cssVisibility($this->block); ?>"
     id="content_<?php echo $field; ?>">

    <a href="#" onclick="popup('http://www.youtube.com/v/<?php echo $this->escape($youtube->value); ?>', <?php echo $width; ?>, <?php echo $height; ?>); return false;">
        <?php echo $this->youtubeThumb($youtube->value, $width, $height); ?>
    </a>

</div>
<?php endif; ?>