<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<div class="block block-content-youtube block-content-youtube-screen <?php echo $this->cssVisibility($this->block); ?>"
     id="content_<?php echo $field; ?>">

    <?php echo $this->youtubeVideo($youtube->value, $width, $height); ?>

</div>
<?php endif; ?>