<?php
$width   = $this->block->getOption('width');
$height  = $this->block->getOption('height');
$field   = $this->block->getOption('field');
$youtube = $this->content->getMetafield($field);

if ($youtube && $youtube->value): ?>

<div <?php echo $this->htmlTagAttribs($this->block, array(
    'class' => 'block-content-youtube-screen', 'id' => 'content_' . $field)); ?>>

    <?php echo $this->youtubeVideo($youtube->value, $width, $height); ?>

</div>
<?php endif; ?>