<? if($this->contents):
   $animeTypes = $this->getContentPairs('anime-type'); ?>

    <? if(!isset($this->options->onlyContents) || !$this->options->onlyContents): ?>

    <? if($this->formFilter): ?>
        <fieldset class="fieldset-form-content-filter<?php echo $this->request ? ' expanded' : ' collapsed' ?>">
            <legend><a href="#" class="form-content-filter-toggle">Busca avançada</a></legend>
            <?php echo $this->formFilter ?>
        </fieldset>
    <? endif ?>

    <div class="block box contents">
        <? if(isset($this->options->title) && $this->options->title): ?>
            <h4><?php echo $this->escape($this->options->title) ?></h4>
        <? endif ?>
        <ul class="contents-cover" id="content_list">
    <? endif ?>
        <? foreach($this->contents as $content): ?>
            <li class="content-item">
                <a href="<?php echo $this->baseUrl($content->slug) ?>" class="link-content">
                    <div class="dt_published"><?php echo $this->dateFormat('dd / MM / yyyy', $content->dt_published) ?></div>
                    <div class="comments" title="<?php echo $content->comments
                            ?> comentário<?php echo $content->comments == 1 ? '' : 's' ?>"
                            ><?php echo $content->comments ? $content->comments : 0 ?></div>
                    <div class="image"><?php echo $this->contentImage($content, 'cover', 114, 160) ?></div>
                    <? if($content->rating): ?>
                    <div class="rating">
                        <? for($i=1;$i<=5;$i++): ?>
                            <div class="<?php echo ($i <= $content->rating) ? 'star-full'
                                : (((float) $i - 0.5 == (float) $content->rating) ? 'star-half' : 'star-empty') ?>"><?php echo $i ?></div>
                        <? endfor ?>
                    </div>
                    <? endif ?>
                    <div class="title"><?php echo $this->escape($this->normalize($content->title)) ?></div>
                    <? if ($content->year): ?>
                        <div class="info">(<?php echo isset($animeTypes[$content->relationships->anime_types[0]])
                                ? $animeTypes[$content->relationships->anime_types[0]] : ''
                            ?><?php echo isset($animeTypes[$content->relationships->anime_types[0]]) && $content->year ? ' - ' : ''
                            ?><?php echo $content->year ?>)</div>
                    <? endif ?>
                </a>
            </li>
        <? endforeach ?>
    <? if(!isset($this->options->onlyContents) || !$this->options->onlyContents): ?>
        </ul>

        <? if(isset($this->options->pages) && $this->options->pages > 1): ?>
            <span class="options" style="display:none"><?php echo Zend_Json::encode($this->options) ?></span>
            <input type="button" class="load-more-contents" value="Exibir mais conteúdo" />
        <? endif ?>

        <br class="clear" />

    </div>
    <? endif ?>
<? endif ?>