<? if($this->contents): ?>
<table class="forums">
<thead>
    <tr>
        <th>Fórum</th>
        <th>Tópicos</th>
        <th>Posts</th>
        <th>Último Post</th>
    </tr>
</thead>
<tbody>
    <? foreach($this->contents as $forum): ?>
    <tr>
        <td class="title">
            <a href="<?php echo $this->baseUrl($forum->slug) ?>">
                <? if($forum->id_group): ?><i class="icon-badge" title="Acesso restrito: <?php echo $forum->getGroup()->groupname ?>"></i><? endif ?>
                <strong><?php echo $this->escape($forum->title) ?></strong>
                <p><?php echo $forum->text ?></p>
            </a>
        </td>
        <td class="counter">
            <a href="<?php echo $this->baseUrl($forum->slug) ?>">
                <?php echo $forum->count_topics ?>
            </a>
        </td>
        <td class="counter">
            <a href="<?php echo $this->baseUrl($forum->slug) ?>">
                <?php echo $forum->count_posts ?>
            </a>
        </td>
        <td class="post-date">
            <a href="<?php echo $this->baseUrl($forum->slug) ?>">
                <? if($forum->lastPost): ?>
                    <div class="avatar">
                        <? if($forum->lastPost->User_avatar): ?>
                            <img src="<?php echo $forum->lastPost->User_avatar ?>" alt=""
                             title="<?php echo $this->escape($forum->lastPost->User_display_name) ?>" />
                        <? else: ?>
                            <?php echo $this->gravatar($forum->lastPost->User_email,
                                array('img_size' => 60, 'default_img' => SITE_URL . '/_site/img/standard-avatar.png'),
                                array('title' => $forum->lastPost->User_display_name)) ?>
                        <? endif ?>
                    </div>
                    <?php echo $this->escape($forum->lastPost->User_display_name) ?><br />
                    <?php echo $this->dateFormat('dd/MM/yy - HH:mm', $forum->lastPost->dt_created) ?>
                <? endif ?>
            </a>
        </td>
    </tr>
    <? endforeach ?>
</tbody>
</table>
<? endif ?>