<? if($this->contents): ?>
    <? if(!isset($this->options->onlyContents) || !$this->options->onlyContents): ?>
    <div class="block box contents">
        <? if(isset($this->options->title) && $this->options->title): ?>
            <h4><?php echo $this->escape($this->options->title) ?></h4>
        <? endif ?>
        <table class="contents-grid">
        <thead>
            <tr>
                <th>Data</th>
                <th>Título</th>
                <th>Ano</th>
                <th>Autor</th>
                <th>Nota</th>
            </tr>
        </thead>
        <tbody id="content_list">
    <? endif ?>
        <? foreach($this->contents as $content): ?>
            <tr class="content-item">
                <td class="dt_published">
                    <?php echo $this->dateFormat('dd/MM/yy', $content->dt_published) ?>
                </td>
                <td class="title">
                    <a href="<?php echo $this->baseUrl($content->slug) ?>" class="link-content">
                        <?/* <span class="image"><?php echo $this->contentImage($content, 'cover', 80, 150) ?></span> */?>
                        <span><?php echo $this->escape($this->normalize($content->title)) ?></span>
                        <? if(isset($content->relationships->anime_types)
                            || isset($content->year)): ?>
                            <span class="info">(<?
                            if (isset($content->relationships->anime_types))
                                echo $this->escape($this->getContent($content->relationships->anime_types[0])->title);
                            ?>)</span>
                        <? endif ?>
                    </a>
                </td>
                <td class="year">
                    <?php echo $content->year ?>
                </td>
                <td class="author">
                    <? if(isset($content->users->author)):
                        $count = count($content->users->author);
                        if ($count > 0) {
                            $authors = '';
                            for($i=0; $i < $count; $i++) {
                                if ($i > 0) {
                                    $authors .= ($i == $count) ? ' e ' : ', ';
                                }
                                $authors .= $this->getUser($content->users->author[$i])->display_name;
                            }
                        }
                    ?>
                    <?php echo $authors ?>
                    <? endif ?>
                </td>
                <td class="rating">
                    <? if($content->rating): ?>
                        <? for($i=1;$i<=5;$i++): ?>
                            <div class="<?php echo ($i <= $content->rating) ? 'star-full'
                                : (((float) $i - 0.5 == (float) $content->rating) ? 'star-half' : 'star-empty') ?>"><?php echo $i ?></div>
                        <? endfor ?>
                    <? endif ?>
                </td>
            </tr>
        <? endforeach ?>
    <? if(!isset($this->options->onlyContents) || !$this->options->onlyContents): ?>
        </tbody>
        </table>

        <? if(isset($this->options->pages) && $this->options->pages > 1): ?>
            <span class="options" style="display:none"><?php echo Zend_Json::encode($this->options) ?></span>
            <input type="button" class="load-more-contents" value="Exibir mais conteúdo" />
        <? endif ?>

        <br class="clear" />
    </div>
    <? endif ?>
<? elseif($this->options->search_result): ?>
<p class="info">Nenhum resultado encontrado.</p>
<? endif ?>