<?php
$filters = Zend_Controller_Front::getInstance()->getRequest()->getParam('filter');
$columnFilters = '';
if ($filters):
    foreach($filters as $filter => $value):
        if ($value) $filters[$filter] = "filter[{$filter}]={$value}";
        else unset($filters[$filter]);
    endforeach;
    $columnFilters = $filters;
    unset($columnFilters['order']);
    $columnFilters = '/?' . implode('&', $columnFilters);
endif;

if ($this->pageCount > 1): ?>
<div class="pagination pagination-centered">
    <ul>
        <?php if($this->previous): ?>
        <!-- First page link -->
        <li class="page page-first<?php echo !$this->previous ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->first)) . $columnFilters; ?>"
                title="Primeira"><i class="icon-step-backward"></i></a></li>

        <!-- Previous page link -->
        <li class="page page-prev<?php echo !$this->previous ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->previous)) . $columnFilters; ?>"
                title="Anterior"><i class="icon-backward"></i></a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li
                class="page page-number<?php echo ($page == $this->current) ? ' active' : ''; ?>">
                <a href="<?php echo $this->url(array('p' => $page)) . $columnFilters; ?>"><?php echo $page; ?></a></li>
        <?php endforeach; ?>

        <?php if($this->next): ?>
        <!-- Next page link -->
        <li class="page page-next<?php echo !$this->next ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->next)) . $columnFilters; ?>"
                title="Próxima"><i class="icon-forward"></i></a>
        </li>

        <!-- Last page link -->
        <li class="page page-last<?php echo !$this->next ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->last)); ?>"
                title="Última"><i class="icon-step-forward"></i></a>
        </li>
        <?php endif; ?>
    </ul>
</div>
<?php endif ?>
