<?php if ($this->pageCount > 1): ?>
<nav class="text-center">
    <ul class="pagination">
        <!-- First page link -->
        <li class="page page-first<?php echo !$this->previous ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->first)); ?>"
                title="Primeira" aria-label="Primeira">&laquo;</a></li>

        <!-- Previous page link -->
        <li class="page page-prev<?php echo !$this->previous ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->previous)); ?>"
                title="Anterior" aria-label="Anterior">&lsaquo;</a></li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <li
                class="page page-number<?php echo ($page == $this->current) ? ' active' : ''; ?>">
                <a href="<?php echo $this->url(array('p' => $page)); ?>"><?php echo $page; ?></a></li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li class="page page-next<?php echo !$this->next ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->next)); ?>"
                title="Próxima" aria-label="Próxima">&rsaquo;</a>
        </li>

        <!-- Last page link -->
        <li class="page page-last<?php echo !$this->next ? ' disabled' : ''; ?>"><a
                href="<?php echo $this->url(array('p' => $this->last)); ?>"
                title="Última" aria-label="Última">&raquo;</a>
        </li>
    </ul>
</nav>
<?php endif; ?>
