<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Tipos de conteúdo</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">Cadastrar tipo de conteúdo</div>
    </div>
    <div class="panel-body">
        <?php echo $this->form; ?>        
    </div>    
</div>