<div class="page-header">
    <h1>
        <div class="btn-group pull-right">
            <a href="<?php echo $this->adminBaseUrl("content/content-type/"
                . "config-page/id/{$this->form->getValue('id_content_type')}");
                ?>" class="btn btn-default">
                <span class="glyphicon glyphicon-wrench"></span> Configurar página
            </a>
        </div>
        
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Tipo de conteúdo</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="row">

    <div class="col-md-9">
        <form method="<?php echo $this->form->getMethod(); ?>" class="form-horizontal"
                      accept-charset="" action="<?php echo $this->form->getAction(); ?>">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Editar tipo de conteúdo: <?php echo $this->escape($this->contentType); ?></h3>
                    <ul class="nav nav-tabs pull-right">
                        <li class="active">
                            <a href="#main_elements" data-toggle="tab">Dados gerais</a>
                        </li>
                        <li>
                            <a href="#content_info" data-toggle="tab">Informacoes</a>
                        </li>
                    </ul>
                </div>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane unstyled active" id="main_elements">
                            <ul class="sortable panel-group list-unstyled" id="accordion_fields" 
                                role="tablist" aria-multiselectable="true">
                                <?php 
                                $metafields = $this->contentType->getMetafields();

                                if($metafields):
                                    foreach($metafields as $metafield):
                                ?>
                                <li class="panel panel-default">

                                    <?php echo $this->partial("content-type/form/field.phtml", array(
                                        'metafield'  => $metafield,
                                        'collapsed'  => true
                                    )); ?>

                                </li>
                                <?php
                                    endforeach;
                                endif;
                                ?>
                            </ul>
                        </div>
                            
                        <div class="tab-pane unstyled" id="content_info">
                            <?php if($this->contentType->id_parent): ?>
                                <?php echo $this->form->getElement('parent')->render(); ?>
                            <?php endif; ?>

                            <?php echo $this->form->getElement('id_content_type')->render(); ?>

                            <?php echo $this->form->getElement('type')->render(); ?>

                            <?php echo $this->form->getElement('plural')->render(); ?>
                        </div>
                    </div><!--.tab-content -->
                </div><!--.panel-body -->
                
                <div class="panel-footer">
                    <?php echo $this->form->getElement('save')->setDecorators(array('ViewHelper')); ?>
                    <?php echo $this->form->getElement('apply')->setDecorators(array('ViewHelper')); ?>
                    <?php echo $this->form->getElement('cancel')->setDecorators(array('ViewHelper')); ?>
                </div>
            </div><!--.panel -->
        </form>
    </div>
    
    <div class="col-md-3">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Adicionar novo campo</h4>
            </div>
            <div class="panel-body">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="add_meta_field_name">Identificação</label>
                        <?php echo $this->formText('add_meta_field_name', '', array(
                            'placeholder' => 'Id do campo',
                            'class'       => 'form-control'
                        )); ?>
                    </div>

                    <div class="form-group">
                        <label for="add_meta_field_type">Tipo de campo</label>
                        <?php echo $this->formRadio('add_meta_field_type', null, null,
                            Content_Model_Metafield::getFieldtypes('field') +
                            Content_Model_Metafield::getFieldtypes('relationship') +
                            Content_Model_Metafield::getFieldtypes('file')
                            , ''); ?>
                    </div>
                    
                    <div class="form-group text-center">
                        <div class="btn-group" role="group">
                            <?php echo $this->formButton('add_meta_field_btn',
                                'Adicionar', array('class' => 'btn btn-lg btn-warning')); ?>
                            <?php echo $this->formReset('rest_meta_field_btn', 
                                'Limpar', array('class' => 'btn btn-lg')); ?>
                        </div>
                    </div>
                    
                    
                    
                </div>
            </div><!--.panel-body -->
        </div><!--.panel -->
    </div>
    
</div>