<?php
$order = $this->form->getElement('order')->getValue();
$orderDesc = strpos($order, ' desc') > 0;
$order = str_replace(' desc', '', $order);
?>
<div class="page-header">
    <div class="btn-group pull-right">
      <a class="btn btn-default" href="<?php echo $this->adminBaseUrl('content/content-type/add'); ?>">
          <span class="glyphicon glyphicon-plus"></span> Cadastrar
      </a>
    </div>
    <h1>
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Tipos de conteúdo</small>
    </h1>
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Tipos de conteúdo cadastrados</h3>
    </div>
    
    <div class="panel-body">
        <div id="filters">
            <?php echo $this->form; ?>
        </div>        
    </div>

    <div class="table-horizontal">
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th<?php echo $order=='id_content_type' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('content/content-type/list/order/id_content_type' . ($order=='id_content_type' && !$orderDesc ? '+desc' : '')); ?>">
                            Id
                            <?php echo $order == 'id_content_type' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th<?php echo $order=='type' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('content/content-type/list/order/type' . ($order=='type' && !$orderDesc ? '+desc' : '')); ?>">
                            Tipo
                            <?php echo $order == 'type' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th<?php echo $order=='plural' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('content/content-type/list/order/plural' . ($order=='plural' && !$orderDesc ? '+desc' : '')); ?>">
                            Plural
                            <?php echo $order == 'plural' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th<?php echo $order=='id_parent' ? ($orderDesc ? ' class="dropup"' : ' class="dropdown"') : ''; ?>>
                        <a href="<?php echo $this->adminBaseUrl('content/content-type/list/order/id_parent' . ($order=='id_parent' && !$orderDesc ? '+desc' : '')); ?>">
                            Tipo pai
                            <?php echo $order == 'id_parent' ? '<span class="caret"></span>' : ''; ?>
                        </a>
                    </th>
                    <th width="50"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $contentType):
                    $parent = $contentType->getParent(); ?>
                    <tr>
                        <td title="<?php echo $contentType->id; ?>">
                            <?php echo $contentType->id; ?>
                        </td>
                        <td title="<?php echo $this->escape($contentType->type); ?>">
                            <?php echo $this->escape($contentType->type); ?>
                        </td>
                        <td title="<?php echo $this->escape($contentType->plural); ?>">
                            <?php echo $this->escape($contentType->plural); ?>
                        </td>
                        <td<?php echo $parent ? ' title="' . $this->escape($parent->type) . '"' : ''; ?>>
                            <?php echo $parent ? $this->escape($parent->type) : ''; ?>
                        </td>
                        <td class="actions">
                             <a href="<?php echo $this->adminBaseUrl("content/content-type/config-page/id/{$contentType->id}"); ?>"
                               title="<?php echo $contentType->getLayoutPage() ? 'Configurar página' : 'Criar página'; ?>"
                               rel="tooltip"><span class="glyphicon glyphicon-wrench"></span></a>

                            <a href="<?php echo $this->adminBaseUrl("content/content-type/edit/id/{$contentType->id}"); ?>"
                               title="Editar" rel="tooltip"><span class="glyphicon glyphicon-edit"></span></a>

                            <?php if($parent): ?>
                            <a href="<?php echo $this->adminBaseUrl("content/content-type/remove/id/{$contentType->id}"); ?>"
                               title="Enviar para a lixeira" rel="tooltip"><span class="glyphicon glyphicon-trash"></span></a>
                            <?php else: ?>
                                <span class="glyphicon glyphicon-trash inactive"></span>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7" class="text-center">
                        Exibindo <?php echo $this->paginator->getCurrentItemCount(); ?> de
                        <?php echo $this->paginator->getTotalItemCount(); ?> itens cadastrados
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
        
    <div class="panel-body"><?php echo $this->paginator; ?></div>
</div>