<div class="page-header">
    <h1>
        <span class="glyphicon glyphicon-file"></span> 
        Conteúdo
        <small>Tipos de conteúdo</small>
    </h1>    
</div>

<?php echo $this->alerts(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Excluir tipo de conteúdo</h3>
    </div>
    <div class="panel-body">
        <h4 class="title">
            <?php echo $this->escape($this->content->type); ?> / 
            <?php echo $this->escape($this->content->plural); ?>
        </h4>
    </div>

    <div class="panel-footer">
        <p><strong>Confirma a exclusão deste tipo de conteúdo?</strong></p>

        <form action="<?php echo $this->url(array('action' => 'remove')); ?>" 
              class="form-actions" method="post">
            <input type="hidden" name="id" value="<?php echo $this->content->id; ?>" />
            <input type="submit" name="delete" value="Excluir" class="btn btn-danger btn-lg" />
            <input type="submit" name="cancel" value="Cancelar" class="btn btn-default btn-lg" />
        </form>
    </div>
</div>